-- 그룹 함수 2

-- SUM, AVG, MAX, MIN, COUNT

SELECT NAME, SUM(PAY)
FROM PROFESSOR;
-- 오류 발생, '단일 그룹의 그룹 함수가 아닙니다' 메시지 팝업

SELECT POSITION, SUM(PAY)
FROM PROFESSOR
GROUP BY POSITION;

-- 학년(GRADE)별 평균 몸무게(WEIGHT)
SELECT * FROM STU;

SELECT 
    GRADE AS 학년,
    AVG(WEIGHT) AS "평균 몸무게"
FROM STU
GROUP BY GRADE;

SELECT
    GRADE AS 학년,
    MAX(WEIGHT) AS "최고 몸무게"
FROM STU
GROUP BY GRADE;


-- COUNT

SELECT COUNT(*) -- 전체 레코드의 개수
FROM STUDENT;

SELECT * FROM PROFESSOR;
SELECT COUNT(BONUS) -- BONUS가 NULL이 아닌 레코드의 수
FROM PROFESSOR;

-- STEP 1. STUDENT 테이블에서 각 학과의 학생 수
SELECT * FROM STUDENT;
SELECT 
    STU_DEPT,
    COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT;

SELECT 
    STU_DEPT,
    COUNT(*)
FROM STUDENT
WHERE COUNT(*) >= 4
GROUP BY STU_DEPT;
-- 불가, COUNT는 그룹화가 끝난 후에 의미 있음

SELECT 
    STU_DEPT,
    COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT
WHERE COUNT(*) >= 4;
-- 불가, WHERE절은 무조건 GROUP 전에 들어가야 함

SELECT 
    STU_DEPT,
    COUNT(*)
FROM STUDENT
GROUP BY STU_DEPT
HAVING COUNT(*) >= 4;

-- STEP 2. 각 학과의 남자 학생수
SELECT 
    STU_DEPT,
    COUNT(*)
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT;

-- STEP 3. 각 학과에서 남자가 2명 이상인 학과명, 학생수 출력
SELECT 
    STU_DEPT,
    COUNT(*)
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT
HAVING COUNT(*) >= 2;




