-- OFFSET ~ FETCH

SELECT * 
FROM TBL_BOARD
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY; -- 1~5


SELECT * 
FROM TBL_BOARD
OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY; -- 6~10


SELECT * 
FROM TBL_BOARD
OFFSET 5 ROWS FETCH NEXT 10 ROWS ONLY; -- 6~15

SELECT * 
FROM TBL_BOARD
ORDER BY CNT DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;
-- 내림차순이므로 CNT 상위 5개 값을 보여줌