SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

SELECT NICKNAME, COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NICKNAME;

SELECT NICKNAME, TITLE
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

-- 각 게시글의 제목, 댓글 개수 출력
-- 게시글이 없는 경우 개수를 0으로 출력
SELECT TITLE 제목, COUNT(COMMENTNO) 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE;

-- 게시글번호, 게시글 제목, 내용, 작성일, 작성자 닉네임, 댓글 개수(없으면0) 출력
SELECT B.BOARDNO 게시글번호, B.TITLE 게시글제목, B.CONTENTS 내용, B.CDATETIME 작성일,NICKNAME 작성자닉네임, COUNT(COMMENTNO) 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
LEFT JOIN TBL_USER U ON C.USERID = U.USERID
GROUP BY B.BOARDNO, B.TITLE, B.CONTENTS, B.CDATETIME, NICKNAME
ORDER BY B.BOARDNO;

SELECT B.BOARDNO, COUNT(COMMENTNO) 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO;

SELECT B.BOARDNO, TITLE, B.CONTENTS, B.CDATETIME, NICKNAME , COMMENT_CNT
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
INNER JOIN (
    SELECT B.BOARDNO, COUNT(COMMENTNO) COMMENT_CNT
    FROM TBL_BOARD B
    LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO
) T ON B.BOARDNO = T.BOARDNO;

-- CASE~WHEN
-- PROFESSOR
-- 1. PROFESSOR 테이블에서 400 이상의 급여를 받으면 A,
-- 300~400 사이면 B, 나머지는 C로 출력
-- 교수이름, 급여등급(A~C)
SELECT * FROM PROFESSOR;

SELECT
    NAME,
    CASE
        WHEN PAY >= 400 THEN 'A'
        WHEN PAY BETWEEN 300 AND 400 THEN 'B'
        ELSE 'C'
    END 급여정보
FROM PROFESSOR;
