-- STUDENT
-- 각 학과의 가장 키가 큰 사람을 구해라 - 학번, 이름, 키

SELECT * FROM STUDENT;

SELECT STU_DEPT, MAX(STU_HEIGHT)
FROM STUDENT
GROUP BY STU_DEPT;

-- 위 쿼리 실행 결과를 조인
-- INNER JOIN 뒤 테이블 입력하는 곳에 ()만들어서 안에 위 쿼리를 넣어준다
SELECT *
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, MAX(STU_HEIGHT) MAX_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT AND S.STU_HEIGHT = T.MAX_HEIGHT;


-- 1. 각 직급별 가장 많은 급여를 받는 교수의 이름, 급여 출력
SELECT * FROM PROFESSOR;

SELECT POSITION, MAX(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT P.POSITION, NAME, PAY
FROM PROFESSOR P
INNER JOIN (
    SELECT POSITION, MAX(PAY) MAX_PAY
    FROM PROFESSOR
    GROUP BY POSITION
) T ON P.POSITION = T.POSITION AND P.PAY = T.MAX_PAY;


-- 2. 본인 부서의 평균 급여보다 높은 급여를 받는 사원의 사번, 이름, 급여 출력
SELECT * FROM EMP;

SELECT DEPTNO, ROUND(AVG(SAL), 0)
FROM EMP
GROUP BY DEPTNO;

SELECT EMPNO, ENAME, SAL, AVG_SAL
FROM EMP E
INNER JOIN (
    SELECT DEPTNO, ROUND(AVG(SAL), 0) AVG_SAL
    FROM EMP
    GROUP BY DEPTNO
) T ON E.DEPTNO = T.DEPTNO AND E.SAL > T.AVG_SAL;
