SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

-- 각 유저가 작성한 게시글의 수(출력 컬럼 : 유저 아이디, 이름, 게시글 개수)

SELECT U.USERID, NAME, COUNT(BOARDNO)
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON U.USERID = B.USERID
GROUP BY U.USERID, NAME;

SELECT B.USERID, NAME, COUNT(BOARDNO)
FROM TBL_BOARD U
RIGHT JOIN TBL_USER B ON U.USERID = B.USERID
GROUP BY B.USERID, NAME;

-- 위 두 명령문 결과가 같음
-- JOIN시에 주체가 되는 테이블이 다를 경우
-- RIGHT를 사용하기 보다는 주체가 되는 테이블을 바꿔주는 것을 권장


-- 각 유저가 작성한 댓글의 수(출력 컬럼 : 유저 아이디, 이름, 댓글 개수)

SELECT U.USERID, NAME, COUNT(COMMENTNO)
FROM TBL_USER U
LEFT JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY U.USERID, NAME;





