-- 조인

-- 오라클 조인, ANSI 조인
-- 조인 => 2개 이상의 테이블을 연결해서 데이터를 도출하는 방법
-- 관계형 데이터베이스의 핵심 문법

SELECT * FROM STUDENT; -- 학생들의 기본 정보 (PK가 포함된 기본 테이블)
SELECT * FROM ENROL; -- 성적 (FK 포함된 참조 테이블)
-- FK => ENROL 테이블의 STU_NO가 STUDENT 테이블 PK 값인 STU_NO를 참조

SELECT * FROM SUBJECT;
-- FK => ENROL 테이블의 SUB_NO가 SUBJECT 테이블 PK 값인 SUB_NO를 참조

SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
INNER JOIN ENROL ON STUDENT.STU_NO = ENROL.STU_NO;
-- 오류 발생

SELECT
    S.STU_NO,
    STU_NAME,
    STU_DEPT,
    ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL ON S.STU_NO = ENROL.STU_NO;

SELECT
    S.STU_NO,
    STU_NAME,
    STU_DEPT,
    ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;
-- 테이블에 별칭을 지정하여 치환하기


SELECT S.*
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT 
    S.*,
    ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;
-- STUDENT 테이블은 전체 COLUMN, ENROL 테이블은 ENR_GRADE COLUMN만 출력

-- 학번, 이름, 학과, 평균점수 출력
SELECT
    S.STU_NO,
    AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO;
-- 이름을 모름

SELECT
    S.STU_NO,
    STU_NAME,
    STU_DEPT,
    AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT;


-- 교수번호, 교수이름, 학과명 출력
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT PROFNO 교수번호, NAME 교수이름, DNAME 학과명
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO;


-- 사번, 이름, 직급, 부서명 출력
SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT EMPNO, ENAME, JOB, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;


-- 학번, 이름, 학과, 시험점수 출력
-- + 과목명

SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.STU_NO 학번, STU_NAME 이름, STU_DEPT 학과, ENR_GRADE 시험점수, SUB_NAME 과목명
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;


-- 같은 COLUMN이 없지만 범위 값으로 상관이 있을 때 JOIN 가능
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL;


-- SELF JOIN (자가 조인)
SELECT * FROM EMP;

SELECT E1.ENAME 근무자, E2.ENAME 관리자
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

SELECT E1.ENAME 근무자, E2.ENAME 관리자
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO
WHERE E1.ENAME = 'ALLEN';

-- SELF JOIN 2
-- 대학 > 학부 > 학과 의 관계
SELECT * FROM DEPARTMENT;

SELECT D1.DNAME, D2.DNAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART
WHERE D1.DNAME = '공과대학';

SELECT D1.DNAME 대학, D2.DNAME 학부, D3.DNAME 학과
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART
WHERE D1.DNAME = '공과대학';

