-- 연습 문제 3 (조인, 서브쿼리, 그룹 함수 등)

-- 1. '컴퓨터정보' 학과에 속한 학생들의 학번, 이름, 평균시험점수를 출력하시오
-- (STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT S.STU_NO 학번, STU_NAME 이름, AVG(ENR_GRADE) 평균시험점수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME;

-- 2. '강종영' 교수의 과목 시험을 본 학생의 학번, 이름, 점수, 과목명을 출력하시오.
-- (STUDENT, ENROL, SUBJECT)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.STU_NO 학번, STU_NAME 이름, ENR_GRADE 점수, SUB_NAME 과목명
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB_PROF = '강종영';

-- 3. 학생들의 이름, 시험을 본 개수를 출력하시오. 
-- - 시험을 안본 사람은 출력을 안하거나 0으로 출력하거나 상관없음.
-- (STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT STU_NAME 이름, COUNT(SUB_NO) "시험을 본 개수"
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;

-- 4. 모든 학생들의 시험 평균 점수보다 높은 평균점수를 가지는 학생들의 학번, 이름, 평균점수를 출력하시오.
-- (STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT *
FROM ENROL
WHERE ENR_GRADE > (
    SELECT STU_NO, STU_NAME, AVG(ENR_GRADE)
    FROM STUDENT
    WHERE ;

SELECT S1.STU_NO 학번, S1.STU_NAME 이름, AVG(ENR_GRADE) 평균점수
FROM STUDENT S1
INNER JOIN ENROL E ON S1.STU_NO = E.STU_NO
GROUP BY S1.STU_NO, STU_NAME, ENR_GRADE;

-- 5. 사원번호, 이름, 급여 등급, 사수(MANAGER)이름을 출력하시오.
-- (EMP, SALGRADE)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;

SELECT E1.EMPNO 사원번호, E1.ENAME 이름, S.GRADE "급여 등급", E2.ENAME "사수 이름"
FROM EMP E1
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

-- 6. 부서별 급여의 평균 등급을 출력하시오. - 부서명, 급여 평균 등급 출력
-- (EMP, SALGRADE, DEPT)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

SELECT DNAME 부서명, ROUND(AVG(GRADE), 1) "급여 평균 등급"
FROM EMP E
INNER JOIN SALGRADE S ON SAL BETWEEN LOSAL AND HISAL
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME;

-- 7. 인문대학에 속한 교수의 이름을 모두 출력하시오.
-- (PROFESSOR, DEPARTMENT)
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT D1.DNAME 대학, D2.DNAME 학부, D3.DNAME 학과, NAME "교수 이름"
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART
INNER JOIN PROFESSOR P ON D3.DEPTNO = P.DEPTNO
WHERE D1.DNAME = '인문대학';

